# This workflow copies the repository's "source" folder to this repository's "target_folder" folder
name: gh-pages cd

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
        
# Sets permissions of the GITHUB_TOKEN to allow writing to this repo
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "docs"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: gh-pages
      url: "https://justinwritescode.com/${{ inputs.deploy_folder }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: get-repo-name
        run: |
          repo_name=$(echo ${{github.workflow.inputs.github_repo}} | cut -d "/" -f 2)
          echo "::set-output name=target_folder::$repo_name"
      - name: Deploy to SubRepo
        # You may pin to the exact commit or the version.
        # uses: aaronbarnaby/deploy-to-subrepo@aee7dd664d56384afd1642c21afaf04993c5af8b
        uses: aaronbarnaby/deploy-to-subrepo@v1.0.2
        env:
          API_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          # Source file from the origin directory
          source: "docs"
          # Destination repository
          target_repo: justinwritescode/docs
          # Directory to push the file to
          target_folder: ${{ github.workflow.jobs.deploy.steps.get-repo-name.outputs.repo_name }} # optional
          # Email for the git commit
          commit_email: justin@thebackroom.app # optional
          # GitHub username for the commit
          commit_name: "justinwritescode" # optional
          # branch to push file to, defaults to main
          target_branch: "main" # optional
          # A custom message for the commit
          commit_message: "CD Docs Push" # optional
